_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
epochs:
    value: 1000
learning_rate:
    value: 0.001
